Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-23.04-arm64"
  config.vm.box_version = "202306.28.0"

  config.vm.provider 'vmware_desktop' do |v|
    v.linked_clone = false
    v.gui = false
  end
  config.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
  config.vm.provision "shell", path: "provision.sh"
end