Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-23.04-arm64"
    config.vm.box_version = "202306.28.0"
    config.vm.hostname = "db01"
    config.vm.network :private_network, ip: "192.168.1.4", :netmask => "255.255.0.0"
    config.vm.network :forwarded_port, guest:3306, host:3307
  
    config.vm.provision "shell", path: "provision.sh" 

    
    config.vm.provider 'vmware_desktop' do |v|
      v.linked_clone = false
      v.gui = false
    end
  
  
  end
  